name: CI-tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Set CHROMEWEBDRIVER environment variable
      run: echo "CHROMEWEBDRIVER=/usr/bin/chromedriver" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Generate Allure Results
      run: |
        mkdir -p allure-results
        cp -r TestResults/*/ allure-results/

    - name: Upload Allure Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
      if: ${{ always() }}
